app/partner/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, PasswordField, HiddenField, RadioField, IntegerField, \
    BooleanField
from wtforms.validators import DataRequired, Length, EqualTo, Optional, InputRequired, ValidationError, Regexp
from wtforms_sqlalchemy.fields import QuerySelectMultipleField, QuerySelectField

from app.models import Category, City


class RegistrationForm(FlaskForm):
    salon_name = StringField('Название салона/мастера', validators=[DataRequired()])
    categories = QuerySelectMultipleField(
        'Категории',
        query_factory=lambda: Category.query.all(),
        get_label='name',
        allow_blank=False
    )
    city = QuerySelectField('Город', query_factory=lambda: City.query.all(), get_label='name', allow_blank=False)
    discount_text = TextAreaField('Текст оффера', validators=[DataRequired()])
    contacts = StringField('Контактные данные', validators=[DataRequired()])
    message_salon_name = StringField('Название салона/мастера для сообщений', validators=[DataRequired()])
    login = StringField('Номер телефона (WhatsApp)', validators=[DataRequired(message='Введите номер телефона')])
    password = PasswordField('Пароль', validators=[DataRequired(), Length(min=6, max=30),
                                                   EqualTo('confirm_password', message='Пароли должны совпадать')])
    confirm_password = PasswordField('Подтвердите пароль', validators=[DataRequired()])
    partner_type = RadioField('Тип партнера', choices=[('salon', 'Салон'), ('individual', 'Частный мастер')],
                              validators=[InputRequired()])
    agree_terms = BooleanField('Я согласен с условиями', validators=[DataRequired()])
    submit = SubmitField('Зарегистрироваться')


class LoginForm(FlaskForm):
    login = StringField('Логин', validators=[DataRequired()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    submit = SubmitField('Войти')


class EditSalonForm(FlaskForm):
    salon_name = StringField('Название салона/мастера', validators=[DataRequired()])
    categories = QuerySelectMultipleField(
        'Категории',
        query_factory=lambda: Category.query.all(),
        get_label='name',
        allow_blank=False
    )
    city = QuerySelectField('Город', query_factory=lambda: City.query.all(), get_label='name', allow_blank=False)
    discount = TextAreaField('Текст скидки', validators=[DataRequired()])
    contacts = StringField('Контактные данные', validators=[DataRequired()])
    message_salon_name = StringField('Название салона/мастера для сообщений', validators=[DataRequired()])
    partner_type = RadioField('Тип партнера', choices=[('salon', 'Салон'), ('individual', 'Частный мастер')],
                              validators=[InputRequired()])
    salon_id = HiddenField('salon_id')
    submit = SubmitField('Сохранить изменения')


class EditUserForm(FlaskForm):
    username = StringField('Номер телефона (WhatsApp)', validators=[DataRequired(), Regexp(r'^7\d{10}$',
                                                                                           message='Введите номер телефона в формате 7XXXXXXXXXX')])
    submit = SubmitField('Сохранить изменения')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Новый пароль', validators=[DataRequired(), Length(min=6, max=30),
                                                         EqualTo('confirm_password',
                                                                 message='Пароли должны совпадать')])
    confirm_password = PasswordField('Подтвердите пароль', validators=[DataRequired()])
    submit = SubmitField('Сбросить пароль')

class AddSalonForm(FlaskForm):
    salon_name = StringField('Название салона/мастера', validators=[DataRequired()])
    categories = QuerySelectMultipleField(
        'Категории',
        query_factory=lambda: Category.query.all(),
        get_label='name',
        allow_blank=False
    )
    city = QuerySelectField('Город', query_factory=lambda: City.query.all(), get_label='name', allow_blank=False)
    discount_text = TextAreaField('Текст оффера', validators=[DataRequired()])
    contacts = StringField('Контактные данные', validators=[DataRequired()])
    message_salon_name = StringField('Название салона/мастера для сообщений', validators=[DataRequired()])
    partner_type = RadioField('Тип партнера', choices=[('salon', 'Салон'), ('individual', 'Частный мастер')],
                              validators=[InputRequired()])
    submit = SubmitField('Добавить салон')

app/partner/__init__.py
from flask import Blueprint

bp = Blueprint('partner', __name__, url_prefix='/partner')

from app.partner import routes  # Импортируем маршруты после определения bp

app/partner/routes.py
import asyncio
import base64
import io
import os
import logging
import random
import string
import requests
from datetime import date, datetime
from collections import defaultdict
from typing import Optional, Dict
from flask import render_template, redirect, url_for, flash, request, send_file, jsonify, session
from flask_login import login_user, logout_user, login_required, current_user
import json
from app import db
from app.models import Partner, PartnerInfo, User, PartnerInvitation, MessageTemplate, ClientSalonStatus, ClientsData, \
    FAQ, PartnerFAQStatus, PartnerAction, Tip, News, PartnerDailyStats
from app.partner import bp
from app.partner.forms import RegistrationForm, LoginForm, EditSalonForm, ResetPasswordForm, EditUserForm, AddSalonForm
from app.partner.services import (
    get_referral_stats,
    get_total_clients_brought_by_referrals,
    get_data_from_partner_daily_stats,
    get_partners_invited_data
)
from app.admin.routes import log_admin_action
from app.qr_code import generate_qr_code
from app.routes import get_template_or_default
from app.services import send_message, send_telegram_notification, create_or_update_partner_amocrm_lead, create_partner_amocrm_contact

def escape_handlebars_braces(text):
    text = text.replace('{', '{{')
    text = text.replace('}', '}}')
    return text


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.login.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash('Вы вошли в систему!', 'success')
            return redirect(url_for('partner.dashboard'))
        else:
            flash('Неверный логин или пароль.', 'danger')
    return render_template('partner/login.html', form=form)


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Вы вышли из системы.', 'info')
    return redirect(url_for('partner.login'))


@bp.route('/')
def index():
    return redirect(url_for('partner.dashboard'))

@bp.route('/stop_impersonating')
def stop_impersonating():
    impersonated_user_id = session.pop('impersonated_user_id', None)
    if impersonated_user_id:
        logout_user()
        admin = User.query.filter_by(username='admin').first() # Получаем пользователя администратора
        login_user(admin) # Авторизуем администратора
        log_admin_action(f'Администратор {current_user.username} вышел из режима редактирования партнера')
        flash('Вы вернулись в админку.', 'success')
    return redirect(url_for('admin.partners'))

def generate_unique_code(length=8):
    """Генерирует уникальный код заданной длины, проверяя его уникальность в базе данных."""
    while True:
        code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=length))
        if not Partner.query.filter_by(unique_code=code).first():
            return code


@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    ref_id = request.args.get('ref')
    if form.validate_on_submit():
        existing_user = User.query.filter_by(username=form.login.data).first()
        if existing_user:
            flash('Пользователь с таким номером телефона уже зарегистрирован.', 'danger')
            return render_template('partner/register.html', form=form)

        try:
            partner_id = generate_unique_salon_id(form.city.data.name)
            new_user = User(username=form.login.data)
            new_user.set_password(form.password.data)
            db.session.add(new_user)
            db.session.flush()
            new_partner_info = PartnerInfo(
                id=partner_id,
                partner_type=form.partner_type.data,
                categories=form.categories.data,
                name=form.salon_name.data,
                discount=form.discount_text.data,
                city_id=form.city.data.id,
                contacts=form.contacts.data,
                message_partner_name=form.message_salon_name.data
            )
            db.session.add(new_partner_info)
            db.session.flush()
            db.session.commit()
            unique_code = generate_unique_code()
            new_partner = Partner(
                user_id=new_user.id,
                referral_link=f"https://sarafan.club/partner-register/?ref={new_user.id}",
                unique_code=unique_code
            )
            new_partner.salons.append(new_partner_info)
            db.session.add(new_partner)
            db.session.commit()
            login_user(new_user)
            if ref_id:
                inviting_partner = Partner.query.filter_by(user_id=ref_id).first()
                if inviting_partner:
                    new_partner_info.invited_by = inviting_partner.id
                    inviting_partner.partners_invited += 1
                    new_invitation = PartnerInvitation(inviting_partner_id=inviting_partner.id,
                                                       invited_partner_id=new_partner.id, invitation_date=date.today())
                    db.session.add(new_invitation)
                    db.session.commit()
            log_partner_action(new_partner.id, 'registration')
            flash(f'Регистрация прошла успешно! Ознакомьтесь с FAQ.', 'success')

            # Отправка уведомления администраторам
            admin = User.query.filter_by(username='admin').first()
            if admin and admin.telegram_chat_ids:
                for chat_id in admin.telegram_chat_ids:
                    message = f"🎉 Новый партнер зарегистрировался!\n\nНомер телефона: {new_user.username}\n\nНазвание салона: {new_partner_info.name}\n\nID: {new_partner_info.id}"
                    asyncio.run(send_telegram_notification(chat_id, message))

            return redirect(url_for('partner.faq'))
        except Exception as e:
            db.session.rollback()
            flash(f'Ошибка при регистрации: {e}', 'danger')
            return render_template('partner/register.html', form=form)
    return render_template('partner/register.html', form=form)


def generate_unique_salon_id(city_name):
    while True:
        city_letter = city_name[0].lower()
        salon_id = f"{city_letter}{random.randint(100000, 999999)}"
        existing_salon = PartnerInfo.query.get(salon_id)
        if not existing_salon:
            return salon_id


@bp.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    partner = Partner.query.filter_by(user_id=current_user.id).first()
    if not partner:
        flash('Вы не зарегистрированы как партнер.', 'danger')
        return redirect(url_for('partner.register'))

    # Получение данных для графиков (для первого салона по умолчанию)
    selected_salon_id = request.args.get('salon_id', partner.salons[0].id if partner.salons else None)
    period = request.args.get('period', 'month')

    total_clients_brought = partner.clients_brought
    total_clients_received = partner.clients_received
    total_partners_invited = partner.partners_invited
    # Получение данных о показах и отказах для всех салонов партнера
    total_offers_shown = 0
    total_offers_rejected = 0
    for salon in partner.salons:
        total_offers_shown += db.session.query(db.func.sum(PartnerDailyStats.offers_shown)).filter(PartnerDailyStats.salon_id == salon.id).scalar() or 0
        total_offers_rejected += db.session.query(db.func.sum(PartnerDailyStats.offers_rejected)).filter(PartnerDailyStats.salon_id == salon.id).scalar() or 0    
    
    # Проверяем, есть ли у партнера салоны
    if not partner.salons:
        flash('У вас нет салонов. Добавьте салон, чтобы продолжить.', 'danger')
        return redirect(url_for('partner.settings'))

    # Оптимизированная функция для получения данных для графиков
    def get_chart_data(chart_type, salon_id, period='month'):
        if chart_type == 'clients_brought':
            return get_data_from_partner_daily_stats(salon_id, 'clients_brought', period)
        elif chart_type == 'offers_shown':
            return get_data_from_partner_daily_stats(salon_id, 'offers_shown', period)
        elif chart_type == 'offers_accepted':
            return get_data_from_partner_daily_stats(salon_id, 'offers_accepted', period)
        elif chart_type == 'offers_rejected':
            return get_data_from_partner_daily_stats(salon_id, 'offers_rejected', period)
        elif chart_type == 'partners_invited':
            return get_partners_invited_data(partner.id, period)
        else:
            return {'labels': [], 'data': []}

    # Получение данных для графиков
    clients_brought_data = get_chart_data('clients_brought', selected_salon_id, period)
    offers_shown_data = get_chart_data('offers_shown', selected_salon_id, period)
    offers_accepted_data = get_chart_data('offers_accepted', selected_salon_id, period)
    offers_rejected_data = get_chart_data('offers_rejected', selected_salon_id, period)
    partners_invited_data = get_chart_data('partners_invited', selected_salon_id, period)

    def get_last_actions(partner_id):
        actions = []
        for salon in partner.salons:
            actions.extend(get_last_actions_for_salon(partner_id, salon.id))
        actions.extend(get_last_actions_for_partner(partner_id))
        actions.sort(key=lambda x: datetime.strptime(x.split(' - ')[-2], '%d-%m-%Y'), reverse=True) 
        return actions[:5]  # Возвращаем не более 5 последних действий

    def get_last_actions_for_salon(partner_id, salon_id):
        actions = []
        clients = ClientsData.query.filter_by(initial_salon_id=salon_id).order_by(
            ClientsData.date.desc()).all()
        for client in clients:
            salon = PartnerInfo.query.get(client.initial_salon_id)
            salon_name = salon.name if salon else 'Неизвестный салон'
            actions.append(

app/templates/partner/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %} - Сарафан</title>

  <!-- Google Font: Open Sans -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <!-- Bootstrap 4 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/css/adminlte.min.css">
  <!-- Bootstrap Select -->
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
  <!-- SweetAlert2 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">

  <!-- Подключаем наши стили -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

  <!-- jQuery -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <!-- Handlebars -->
  <script src="https://cdn.jsdelivr.net/npm/handlebars@latest/dist/handlebars.min.js"></script>
  <!-- Moment.js -->
  <script src="https://cdn.jsdelivr.net/npm/moment@2.29.1/moment.min.js"></script>
  <!-- SweetAlert2 -->
  <script src="{{ url_for('static', filename='js/sweetalert2.js') }}"></script>
  <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">

  <!-- ApexCharts CDN -->
  <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

  {% block head %}{% endblock %}
</head>
<body class="hold-transition sidebar-mini sidebar-collapse">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('partner.logout') }}">Выйти</a>
        </li>
      {% endif %}
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ url_for('partner.dashboard') }}" class="brand-link">
      <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo"
           class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">САРАФАН</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
            data-accordion="false">
          <li class="nav-item">
            <a href="{{ url_for('partner.dashboard') }}"
               class="nav-link {% if request.endpoint == 'partner.dashboard' %}active{% endif %}">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Главная
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('partner.settings') }}"
               class="nav-link {% if request.endpoint == 'partner.settings' %}active{% endif %}">
              <i class="nav-icon fas fa-cog"></i>
              <p>
                Настройки
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('partner.profile') }}"
               class="nav-link {% if request.endpoint == 'partner.profile' %}active{% endif %}">
              <i class="nav-icon fas fa-user"></i>
              <p>
                Профиль
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="{{ url_for('partner.referrals') }}"
               class="nav-link {% if request.endpoint == 'partner.referrals' %}active{% endif %}">
              <i class="nav-icon fas fa-users"></i>
              <p>
                Реф. программа
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('partner.faq') }}"
               class="nav-link {% if request.endpoint == 'partner.faq' %}active{% endif %}">
              <i class="nav-icon fas fa-question-circle"></i>
              <p>
                FAQ
              </p>
            </a>
          </li>
  {% if 'impersonated_user_id' in session %}
    <li class="nav-item">
      <a href="{{ url_for('partner.stop_impersonating') }}" class="nav-link">
        <i class="nav-icon fas fa-sign-out-alt"></i>
        <p>
          Вернуться в админку
        </p>
      </a>
    </li>
  {% endif %}
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">{% block page_title %}{% endblock %}</h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        {% block content %}
        {% endblock %}
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- Default to the left -->
    <strong>2024 <a href="#">Сарафан</a>.</strong>
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->
<script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>
<!-- Bootstrap 4 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/js/adminlte.min.js"></script>
<!-- Bootstrap Select -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<!-- Подключаем наши скрипты -->
<script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
<script>
  // Получаем flash-сообщения ДО загрузки DOM
  {% with messages = get_flashed_messages(with_categories=true) %}
    let messages = [];
    {% if messages %}
      messages = {{ messages|tojson|safe }};
    {% endif %}
  {% endwith %}

  $(document).ready(function () {
    // Используем массив messages внутри $(document).ready()
    if (messages.length > 0) {
      messages.forEach(function (message) {
        let icon = 'info';
        switch (message[0]) {
          case 'success':
            icon = 'success';
            break;
          case 'error':
            icon = 'error';
            break;
          case 'warning':
            icon = 'warning';
            break;
        }

        // Используем Toast вместо Swal.fire()
        const Toast = Swal.mixin({
          toast: true,
          position: "top-end",
          showConfirmButton: false,
          timer: 3000,
          timerProgressBar: true,
          didOpen: (toast) => {
            toast.onmouseenter = Swal.stopTimer;
            toast.onmouseleave = Swal.resumeTimer;
          }
        });

        Toast.fire({
          icon: icon,
          text: message[1]
        });
      });
    }
  });
</script>
</body>
</html>

app/templates/partner/create_salon.html
{% extends 'partner/base.html' %}

{% block title %}Добавить салон{% endblock %}

{% block page_title %}Добавить салон{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Добавить салон</h3>
                    </div>
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        <div class="card-body">
                            <div class="form-group">
                                {{ form.salon_name.label(class="form-label") }}
                                {{ form.salon_name(class="form-control") }}
                            </div>
                            <div class="form-group">
                                {{ form.partner_type.label(class="form-label") }}
                                {% for subfield in form.partner_type %}
                                    <div class="form-check">
                                        {{ subfield(class="form-check-input") }}
                                        {{ subfield.label(class="form-check-label") }}
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="form-group">
                                {{ form.categories.label(class="form-label") }}
                                {{ form.categories(class="form-control selectpicker", multiple=True, data_live_search="true", data_size="10", title="Выберите категории") }}
                            </div>
                            <div class="form-group">
                                {{ form.city.label(class="form-label") }}
                                {{ form.city(class="form-control selectpicker", data_live_search="true", title="Выберите город") }}
                            </div>
                            <div class="form-group">
                                {{ form.discount_text.label(class="form-label") }}
                                {{ form.discount_text(class="form-control") }}
                            </div>
                            <div class="form-group">
                                {{ form.contacts.label(class="form-label") }}
                                {{ form.contacts(class="form-control") }}
                            </div>
                            <div class="form-group">
                                {{ form.message_salon_name.label(class="form-label") }}
                                {{ form.message_salon_name(class="form-control") }}
                            </div>
                            <div class="form-group">
                                {{ form.submit(class="btn btn-primary") }}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/partner/detailed_stats.html
{% extends 'partner/base.html' %}

{% block title %}Детальная статистика{% endblock %}

{% block page_title %}Детальная статистика{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            {% if stat_type == 'brought' %}
                                Приведенные клиенты
                            {% elif stat_type == 'received' %}
                                Полученные клиенты
                            {% elif stat_type == 'invited' %}
                                Приглашенные партнеры
                            {% endif %}
                        </h3>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Имя</th>
                                <th>Номер телефона</th>
                                <th>Дата</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for client in clients %}
                                <tr>
                                    <td>
                                        {% if stat_type == 'invited' %}
                                            {{ client.salon.name }}
                                        {% else %}
                                            {{ client.client_name }}
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if stat_type == 'invited' %}
                                            {{ client.salon_id }}
                                        {% else %}
                                            {{ client.chat_id }}
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if stat_type == 'invited' %}
                                            {% set invitation = PartnerInvitation.query.filter_by(inviting_partner_id=current_user.partner[0].id, invited_partner_id=client.id).first() %}
                                            {# Получаем первый элемент списка current_user.partner #}
                                            {{ invitation.invitation_date.strftime('%d.%m.%Y') if invitation else '-' }}
                                        {% else %}
                                            {{ client.date.strftime('%d.%m.%Y') }}
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/partner/faq.html
{% extends 'partner/base.html' %}

{% block title %}FAQ{% endblock %}

{% block page_title %}FAQ{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Часто задаваемые вопросы</h3>
                    </div>
                    <div class="card-body">
                        <div class="accordion" id="faqAccordion">
                            {% for faq in faqs %}
                                <div class="card">
                                    <div class="card-header" id="heading{{ faq.id }}">
                                        <h2 class="mb-0">
                                            <button class="btn btn-link" type="button" data-toggle="collapse"
                                                    data-target="#collapse{{ faq.id }}" aria-expanded="true"
                                                    aria-controls="collapse{{ faq.id }}">
                                                {{ faq.question }}
                                            </button>
                                        </h2>
                                    </div>

                                    <div id="collapse{{ faq.id }}" class="collapse {% if loop.first %}show{% endif %}"
                                         aria-labelledby="heading{{ faq.id }}" data-parent="#faqAccordion">
                                        <div class="card-body">
                                            {{ faq.answer }}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        {% if not partner.faq_status.has_read_faq %}
                            <form method="POST" action="{{ url_for('partner.confirm_faq') }}">
                                <div class="form-check mt-3">
                                    <input class="form-check-input" type="checkbox" id="confirmRead" name="confirmRead"
                                           required>
                                    <label class="form-check-label" for="confirmRead">
                                        Я ознакомился(ась) с FAQ
                                    </label>
                                </div>
                                <button type="submit" class="btn btn-primary mt-3">Подтвердить</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}